# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Discourse中文网
baseurl:             ''

sass:
  style: :compressed
